------------------------------------------------------------------------------------------
https://www.freecodecamp.org/news/how-to-become-a-junior-software-engineer-in-6-months/
https://fullstackopen.com/en/about/
------------------------------------------------------------------------------------------
-----------------------------
NARAINE PATH - 80 DAYS
-----------------------------
Jan 01 - March 20 [daily 7hrs]
-----------------------------
Html + Browser = 2 days
-----------------------------
Css3 = 3 Days
-----------------------------
Scss Sass = 2 days
-----------------------------
BS5 = 3 days
-----------------------------
TW = 3 days
-----------------------------
Git + Github = 2 days
-----------------------------
Vanila JS = 5 days
-----------------------------
JqueryJs + Website support
Js Libraries = 6 days
-----------------------------
ReactJs = 7 days
-----------------------------
NodeJs = 4 days
-----------------------------
TS = 2 days
-----------------------------
API / Postman / GraphQL /
REST API = 3 Days
-----------------------------
PHP = 4 days
----------------------------
SQL MySQL = 4 days
----------------------------
DBMS = 4 days
----------------------------
AWS + Jenkins = 4 days
----------------------------

-----------------------------------------------
naraine-developer.website Path
-----------------------------------------------
ETA = Jan 31st

Common = Preloader / Top Button / Header / Footer / Color / Font
Home page =  Intro section / Work Experience / Skill Sets / Education / Achieved / Explore to other pages
Contact = Form / Details / Validation
Front End = Overview + Js + Js libraries + Css + Html + Projects
React Js = Overview + Install + issues faced + Projects
BackEnd/DBMS = Nodejs + MongoDB 
Personal = Hobbies + Movies + Songs
Sports = Boxing + Cricket 
Family + Friends = Explore it + Gallery

-----------------------------------------------
LMS Path
-----------------------------------------------
https://syndicode.com/blog/how-to-build-a-learning-management-system/





