---------------------------------------------------------------------
NodeJs Installation
---------------------------------------------------------------------
1. sudo apt update & upgrade , Check node & npm version then download https://nodejs.org/download/release/latest-v18.x/ - Download tar.xz file
(For Linux)

2. Extract locally , rename the extracted folder to node & Open the terminal , redirect to the folder the node has been extracted . Run the
command -> sudo cp -r node/{bin,include,lib,share} /usr/ which install the local file to the system.

3. Check node & npm version , node -v , npm -v

yarn-> alternative -> https://www.copycat.dev/blog/yarn-vs-npm/  , https://www.hostinger.com/tutorials/how-to-install-yarn  
sudo npm install --global yarn 
yarn --version


------------------
Form Validation
------------------
https://www.toptal.com/nodejs/smart-node-js-form-validation 
