---------------------------------------------------------------------
ReactJS Project Install + Load
---------------------------------------------------------------------
1. sudo npm --location=global install create-react-app for installing globally & check create-react-app --version

2. npx create-react-app folder name to create a folder of predefined npm
scripts to execute react project

3. Once installation is completed , happy hacking ! message will be displayed
and open the terminal cd folder name && code . && npm start.

Alternative method from CRA:
4. https://medium.com/@dawid.niegrebecki/create-react-app-is-dead-what-to-use-instead-fcdd46b70295#:~:text=It%20was%20the%20easiest%20way,solution%20for%20creating%20React%20applications. 

https://liaogg.medium.com/its-time-to-stop-using-create-react-app-a99917dbfc  

npm create vite@latest
React install is a better way.

-------------------
Js For React
-------------------
Closures = Effective Apply = State & Scope manage
DOM manipulation
Higher Order Functions
Callbacks , Promises, Async , Await - Asynchronous programming
ECMAScript - latest feature & update
this & arrow function
Event Listener - interactive applications
Browser based JS debug tools
Prototype Based , difference between = inheritance model & classical model

------------------------
ReactJS Topics
------------------------
Reactjs - CLI Tools [Vite , CRA] , Components [Class, Functional, 
Basic (Jsx , states vs props , conditional rendering , composition), 
Rendering [Component Life Cycle , List and keys , Render props, Refs , 
Events , Higher order components] , Hooks [useState, useEffect, Custom 
Hooks - useCallBack/useRef/useMemo/useReducer/useContext] , Routers 
[react router /reach router] , State Management - Recoil , MobX, Redux , 
Styling - Emotion / Styled / Tailwind / Mantine , API calls - 
GraphQL[Apollo,Relay] / REST [react-query , Axios, SWR] , Testing [Cypress,Jest] ,
Frameworks - Remix / NextJS , Forms [React hook Forms , Final Form, Suspense , 
Portals , error boundaries] , Mobile Apps [React native]
